name: pocketbase_server_flutter_example
description: Demonstrates how to use the pocketbase_server_flutter plugin.
version: 0.1.0+1
publish_to: "none"

environment:
  sdk: ">=3.0.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  path_provider: ^2.1.5
  pocketbase_server_flutter:
    path: ../

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
