name: pocketbase_server_flutter
description: Start Pocketbase Server directly from Android/IOS with flutter
version: 0.0.2
homepage: https://github.com/rohitsangwan01/pocketbase_server_flutter
repository: https://github.com/rohitsangwan01/pocketbase_server_flutter
issue_tracker: https://github.com/rohitsangwan01/pocketbase_server_flutter/issues

environment:
  sdk: ">=3.0.1 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.rohit.pocketbase_server_flutter
        pluginClass: PocketbaseServerFlutterPlugin
      ios:
        pluginClass: PocketbaseServerFlutterPlugin
